-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Table: Tables (Restaurant Tables)
create table public.tables (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null, -- e.g. "T-1"
  capacity integer default 4,
  zone text default 'Main Hall', -- e.g. "Main Hall", "Terrace"
  status text default 'available' -- 'available', 'occupied', 'reserved'
);

-- Table: Reservations
create table public.reservations (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date date not null,
  time time not null,
  customer_name text not null,
  customer_phone text,
  guests integer default 2,
  status text default 'confirmed', -- 'confirmed', 'pending', 'cancelled', 'completed'
  notes text,
  table_id bigint references public.tables(id)
);

-- Row Level Security (RLS)
alter table public.tables enable row level security;
alter table public.reservations enable row level security;

-- Policies (Allow public read/write for demo purposes, strict policies would require Auth)
create policy "Allow public read access" on public.tables for select using (true);
create policy "Allow public read access" on public.reservations for select using (true);
create policy "Allow public insert" on public.reservations for insert with check (true);
create policy "Allow public update" on public.reservations for update using (true);

-- Seed Data
insert into public.tables (name, capacity, zone, status) values
  ('T-1', 4, 'Main Hall', 'available'),
  ('T-2', 2, 'Main Hall', 'occupied'),
  ('T-3', 4, 'Window', 'available'),
  ('T-4', 6, 'Window', 'reserved'),
  ('T-5', 2, 'Terrace', 'available'),
  ('T-6', 4, 'Terrace', 'available');

insert into public.reservations (date, time, customer_name, guests, status, table_id) values
  (CURRENT_DATE, '19:00', 'John Doe', 2, 'confirmed', 3),
  (CURRENT_DATE, '20:00', 'Jane Smith', 4, 'pending', 1),
  (CURRENT_DATE - 1, '18:30', 'Alice Brown', 2, 'completed', 2);
